import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./component/header";
import Sidebar from "./component/sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <body className={inter.className}>
        <Header />
        <div className="flex w-full">
          {/* <div className="w-[218px] bg-slate-300 h-[100vh]"> */}
          <Sidebar />

          {/* </div> */}
          <div className="flex w-full">
            <div className='w-0 sm:w-64' ></div>
            {children}
          </div>

        </div>


      </body>
    </html>
  );
}
